# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 383ab648e078fb2e1f12351b449cf2fce6470fda64eb7498100c9775ac3dc1c04d5523ec59c390a252cf697fc69964a55ca382554c8202db974f20d927f923ae

test:
  secret_key_base: ef5d8bdefb829385832d5d14604bef1a6b3c471ff707a65e47483d34051d7e470bb5de0dc33f29a6f0e2f7949c21d08cd4a4ab50ed4b96527e3dc1d4ab320e41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
